import Head from "next/head";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>My Posts</h1>

        <ul className={styles.post}>
          <li>
            <p className={styles.postsContent}>
              I’m working in Figma, designing a website to display all of my
              tweets!
            </p>
            <p className={styles.postsDate}>01/24/2022</p>
          </li>

          <li>
            <p className={styles.postsContent}>
              I’m working in Figma, designing a website to display all of my
              tweets!
            </p>
            <p className={styles.postsDate}>01/24/2022</p>
          </li>

          <li>
            <p className={styles.postsContent}>
              I’m working in Figma, designing a website to display all of my
              tweets!
            </p>
            <p className={styles.postsDate}>01/24/2022</p>
          </li>
        </ul>

        <form>
          <textarea className={styles.formContent}></textarea>

          <button className={styles.formButton}>Add New Post</button>
        </form>
      </main>
    </div>
  );
}
